services:
  postgres:
    image: docker.io/postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  customers_service_app:
    build:
      context: ./customers
      dockerfile: Containerfile
    container_name: customers_service
    depends_on:
      postgres:
    environment:
      # DATABASE_URL: postgresql+asyncpg://admin:adminpassword@postgres:5432/appdb
      # SECRET_KEY: your-secret-key-here
      # ALGORITHM: HS256
      # ACCESS_TOKEN_EXPIRE_MINUTES: 30
    volumes:
      - ./customers:/app
    ports:
      - "5001:5001"
    restart: always


volumes:
  postgres_data:
